version: '3.8'

services:
  # Laravel + Vue.js Container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_vue_app
    ports:
      - "8000:8000"
    volumes:
      - C:\Probando\appsai:/var/www
    depends_on:
      - mysql
    networks:
      - app_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:randomkey
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  # MySQL Database Container
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # phpMyAdmin (Optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: